version: '3.9'

services:
  nginx:
    image: docker.io/library/nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    network_mode: "host"
    restart: always

  # rosblox-studio:
  #   image: ghcr.io/rosblox/studio:latest
  #   volumes:
  #     - ./studio/layout.json:/src/layout.json
  #   ports:
  #     - 8080:8080
  #   restart: always

#  ros-rosbridge-suite:
#    image: ghcr.io/rosblox/ros-rosbridge-suite:humble
#    ports:
#      - 9090:9090
#    restart: always
#    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml

  ros-ina220:
    image: ghcr.io/rosblox/ros-ina220:humble
    devices:
      - "/dev/i2c-4:/dev/i2c-1"
    restart: always
    network_mode: "host"
    command: ros2 run ros_ina220 ros_ina220_publisher
    environment:
      - ROS_DOMAIN_ID=23

  # ros-cpu-temperature:
  #   image: ghcr.io/rosblox/ros-cpu-temperature:humble
  #   restart: always
  #   network_mode: "host"
  #   command: ros2 run ros_cpu_temperature ros_cpu_temperature_publisher
  #   environment:
  #     - ROS_DOMAIN_ID=23


  ros-joy-linux:
    image: ghcr.io/rosblox/ros-joy-linux:humble
    volumes:
      - /dev/input:/dev/input
    privileged: true
    restart: always
    network_mode: "host"
    command: ros2 run joy_linux joy_linux_node
    environment:
      - ROS_DOMAIN_ID=23

  rtklib:
    image: ghcr.io/rosblox/rtklib:latest
    restart: always
    command: str2str -in ntrip://$NTRIP_USER:$NTRIP_PASSWORD@www.swipos.ch:2101/MSM_GISGEO_LV95LHN95 -b 1 -out tcpcli://192.168.60.1:6666

  ros-septentrio-gnss-driver:
    image: ghcr.io/rosblox/ros-septentrio-gnss-driver:humble
    restart: always
    network_mode: "host"
    command: ros2 run septentrio_gnss_driver septentrio_gnss_driver_node --ros-args -p device:=tcp://192.168.60.1:28784 -p polling_period.pvt:=100 -p frame_id:="gnss_link" -p rtk_settings.ip_server_1.send_gga:="sec1" -p rtk_settings.ip_server_1.port:=6666 -p rtk_settings.ip_server_1.id:="IPS1"
    environment:
      - ROS_DOMAIN_ID=23

  ros-winch-control:
    image: ghcr.io/rosblox/ros-winch-control:humble
    volumes:
      - /home/rock/.ros:/tmp
    restart: always
    network_mode: "host"
    command: ros2 launch winch_control noodle.launch.py
    environment:
      - ROS_DOMAIN_ID=23

  ros-imu-tools:
    image: ghcr.io/rosblox/ros-imu-tools:humble
    volumes:
      - ./imu_tools/imu_filter_madgwick.launch.py:/colcon_ws/install/imu_filter_madgwick/share/imu_filter_madgwick/launch/imu_filter_madgwick.launch.py
      - ./imu_tools/imu_filter_madgwick.yaml:/colcon_ws/install/imu_filter_madgwick/share/imu_filter_madgwick/config/imu_filter_madgwick.yaml
      - ./imu_tools/imu_complementary_filter.launch.py:/colcon_ws/install/imu_complementary_filter/share/imu_complementary_filter/launch/imu_complementary_filter.launch.py
      - ./imu_tools/imu_complementary_filter.yaml:/colcon_ws/install/imu_complementary_filter/share/imu_complementary_filter/config/imu_complementary_filter.yaml
    network_mode: "host"
    restart: always
    # command: ros2 launch imu_filter_madgwick imu_filter_madgwick.launch.py
    command: ros2 launch imu_complementary_filter imu_complementary_filter.launch.py
    environment:
      - ROS_DOMAIN_ID=23

  ros-lsm6dsox-lis3mdl:
    image: ghcr.io/rosblox/ros-lsm6dsox-lis3mdl:humble
    devices:
      - "/dev/i2c-3:/dev/i2c-1"
    restart: always
    network_mode: "host"
    command: ros2 run ros_lsm6dsox_lis3mdl ros_lsm6dsox_lis3mdl_publisher
    environment:
      - ROS_DOMAIN_ID=23

  ros-as5048b_1:
    image: ghcr.io/rosblox/ros-as5048b:humble
    restart: always
    devices:
      - /dev/i2c-1:/dev/i2c-1
    network_mode: "host"
    command: ros2 run ros_as5048b ros_as5048b_publisher --ros-args -p i2c_device:=1 -p i2c_address:=0x42
    environment:
      - ROS_DOMAIN_ID=23
  
  ros-as5048b_2:
    image: ghcr.io/rosblox/ros-as5048b:humble
    restart: always
    devices:
      - /dev/i2c-1:/dev/i2c-1
    network_mode: "host"
    command: ros2 run ros_as5048b ros_as5048b_publisher --ros-args -p i2c_device:=1 -p i2c_address:=0x44
    environment:
      - ROS_DOMAIN_ID=23



  ros-pca9685-ros2-control:
    image: ghcr.io/rosblox/ros-pca9685-ros2-control:humble
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    volumes:
      - ./pca9685_ros2_control/mixed_controller.yaml:/colcon_ws/install/pca9685_ros2_control_example/share/pca9685_ros2_control_example/config/mixed_controller.yaml    
      - ./pca9685_ros2_control/robot_description:/colcon_ws/install/pca9685_ros2_control_example/share/pca9685_ros2_control_example/urdf
      - ./pca9685_ros2_control/ros2_control_bringup.launch.py:/colcon_ws/install/pca9685_ros2_control_example/share/pca9685_ros2_control_example/launch/mixed_example.launch.py

    restart: always
    network_mode: "host"
    command: ros2 launch pca9685_ros2_control_example mixed_example.launch.py
    environment:
      - ROS_DOMAIN_ID=23


  ros-robot-localization:
    image: ghcr.io/rosblox/ros-robot-localization:humble
    restart: always
    network_mode: "host"
    volumes:
      - ./robot_localization/ukf.yaml:/opt/ros/humble/share/robot_localization/params/ukf.yaml
      - ./robot_localization/gnss_imu_localization.launch.py:/opt/ros/humble/share/robot_localization/launch/ukf.launch.py
    command: ros2 launch robot_localization ukf.launch.py
    environment:
      - ROS_DOMAIN_ID=23


#  ros-navigation2:
#    image: ghcr.io/rosblox/ros-navigation2:humble
#    volumes:
#      - ./nav2_bringup/nav2_bringup_launch.py:/opt/ros/humble/share/nav2_bringup/launch/nav2_bringup_launch.py
#      - ./nav2_bringup/nav2_params.yaml:/opt/ros/humble/share/nav2_bringup/params/nav2_params.yaml
#      - ./nav2_bringup/goat_world.yaml:/opt/ros/humble/share/nav2_bringup/maps/goat_world.yaml
#      - ./nav2_bringup/goat_world_empty.pgm:/opt/ros/humble/share/nav2_bringup/maps/goat_world_empty.pgm
#      - ./nav2_bringup/navigate_to_pose_w_replanning_rolling_and_recovery.xml:/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml
#    restart: always
#    network_mode: "host"
#    command: ros2 launch nav2_bringup nav2_bringup_launch.py
#    environment:
#      - ROS_DOMAIN_ID=23
