imu_complementary_filter:
  ros__parameters:
    publish_tf: true
    reverse_tf: true
    fixed_frame: "odom_from_imu_debug"
    constant_dt: 0.0
    publish_debug_topics: false
    gain_acc: 0.1
    gain_mag: 0.1
    bias_alpha: 0.1
    do_bias_estimation: true
    do_adaptive_gain: true
    use_mag: true
